name: dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - xarray
  - numpy
  - zarr
  - matplotlib
  - scipy
  - regionmask
  - geopandas
  - jupyter
  - ipykernel
  - pip
  - pip:
    - # Add any pip-only packages here if needed
